### ISSUE TITLE
problems on debian stretch 

### ISSUE THREAD

**Issue by djstauffer** [hbekel/bashrun2#2]
I'm running bashrun2 version 0.2.3 under debian stretch.  It works just fine for me on debian jessie, but on one of my stretch machines I get these errors when running bashrun2:

config.bash: line 7: [1]=: command not found
config.bash: line 8: [1]=: command not found
template.bash: line 7: [1]=-name %n: command not found
template.bash: line 8: [1]=: command not found
terminal.bash: line 7: [1]=: command not found
terminal.bash: line 8: [1]=: command not found
mode.bash: line 7: [1]=xterm: command not found
mode.bash: line 8: [1]=: command not found

I believe this has something to do with quoting, but I'm not sure how to fix it.   I have one other debian stretch machine which was upgraded from jessie, and that one works fine.   However the machine with the problem was a clean install of debian stretch.  I'm wondering if there are some differences in the way the bash environment is set up that might be the cause of the problem.

Any help you can give on this would be greatly appreciated.  I would very much like to continue to use bashrun2 on stretch.

**Comment by hbekel** [comment]
I'm aware of this problem, this is due to (probably subtle) changes in bash 4.4. I haven't yet found time to investigate this. The problem occurs when the configuration is being cooked (or recooked), i.e. when you change the configuration or run bashrun for the first time. So your configuration from jessie will keep running fine on strech unless you change it... Unfortunate, I know.

I will look into this, but that may take some time, I haven't really looked at the code for a long time.

**Comment by djstauffer** [comment]
OK, thanks.

So, if I copied my ~/.config/bashrun2 dir from the machine that is working to the broken one, would it possibly fix the broken one temporarily?  Or are there files in other locations I would also need to copy?

**Comment by djstauffer** [comment]
oh, sorry, I meant ~/.cache/bashrun2

**Comment by hbekel** [comment]
You'll need to copy both ~/.config/bashrun2/ and ~/.cache/bashrun2 unless the configuration files are already identical on both machines, otherwise bashrun2 will try to reconfigure (and thus recreate) files in .cache/bashrun2.

I have now identified the problem and fixed it for bash 4.4 on my machine. I still have to make it work for both bash 4.3 and earlier and bash 4.4, though. I'll look into that tomorrow.

**Comment by djstauffer** [comment]
Awesome!

Thanks for identifying and fixing the problem so quickly.  I'll keep an eye out for when you get the fixes checked in so I can grab the updates.

**Comment by hbekel** [comment]
Checked in the fix, please test.

**Comment by djstauffer** [comment]
Yup, it works here -- thanks again!

**Comment by hbekel** [comment]
Ok, then I'll close this and prepare a new release soon. Thanks for pushing me to fix this, and let me know if anything else is amiss :)
