### ISSUE TITLE
Feature request: add support for st

### ISSUE THREAD

**Issue by KaffeMyers** [hbekel/bashrun2#8]
Hi,
I've been running bashrun2 with urxvt with GREAT SUCCESS for a long time, but I'm moving away from urxvt in favor of st. Would like to continue using bashrun2, but things such as WM_CLASS doesn't get set properly and creates a bit of a conundrum. I have a project that would suffer if that isn't set to something unique, so of course the best for me personally would be if bashrun simply started supporting st fully. 

This is a luxury request and I'm well aware of it, but mayhaps can this request be bequeathe a spark of delight? Also, if I've simply missed a setting, I'll gladly take a lecture. 

Thanks for this nice little run-er!

**Comment by hbekel** [comment]
Hi,

I assume that you're already passing a generic terminal command line for your run-dialog's --terminal option since that is the only way you could have gotten bashrun to use a different terminal from those explicitly supported (See the manual page section GENERIC TERMINAL SUPPORT).

st has a rather limited set of command line options compared to the classic terminals like xterm or urxvt, so the following should already be a rather complete terminal template:

+mode run-dialog
  --terminal 'st -c %n -n %n -g %g -f %f %o -e %*'

As you can see, the mode's name %n ("bashrun-run-dialog") will be passed as the WM_CLASS class property (via st option -c) and as the WM_CLASS name property (via st option -n). Setting both portions of the WM_CLASS property to this same value is what bashrun usually does for the terminal window. Not sure if that's what you mean by "setting WM_CLASS properly".

A similar template should be sufficient for +terminal objects, i.e. to launch programs in new st instances.

In any case, this is as much as "support for st" would go from bashruns point of view at the moment. Note though that this is probably not enough to make every bashrun feature work with st, especially not those relying on more exotic terminal behaviours found in xterm or urxvt. Those would probably need some tinkering with st itself, maybe via config.h.

Disclaimer: If I'm a bit vague here it is because I haven't looked into this project for a long time, and quite frankly it is a deep and somewhat over-engineered rabbit hole i went down back in the day. I am also hardly familiar with st as well.

Let me know if this helps, or what else is amiss. In any case, I'm always glad to hear that somebody still uses this. 

EDIT: Typo

**Comment by KaffeMyers** [comment]
I've just read your reply and it seems to be very useful information. I will look into this!

Well, I'll take you on your word on the whole over-engineered part as I have yet to look at the bashrun source code, but I do like the idea and user experience of it very much. :)

**Comment by scorpp** [comment]
I use bashrun2 with st for several month now, all good. Configuration is similar to what hbekel has shown.

I'm primarily using it just as a classic launcher, so utilising not more than ~30%  of what it does, so can't confirm some more sophisticated features work as expected.

**Comment by KaffeMyers** [comment]
I'm not really getting this to work. I changed it in the core file, but I get the same result.
@scorpp Would you mind sharing the steps you took?

**Comment by scorpp** [comment]
edit `~/.config/bashrun2/bashrun2.rc`
```
+configure-modes () {

    # The default "run-dialog" mode:

    +mode run-dialog

      # Terminal to use for bashrun. Supported terminals are xterm,
      # urxvt, urxvtc, mrxvt, mlterm and aterm:
      #--terminal 'xterm'
      --terminal 'st -n %n -g %g %o -e %*'
```
then
```
$ bashrun2 quit
$ bashrun2 show
```

if that doesn't help, try `rm -rf ~/.cache/bashrun2/`

**Comment by KaffeMyers** [comment]
Fantastic! It is doing the thing.

For any future viewers, a closing bracket is missing in the bashrun2.rc in the example above

EDIT: Just realized there are now other issues instead, like enter not making the run-dialog exit and history file being unreadable. I'm gonna investigate why this is, buf if you know of any other steps you took to make it work as expected, feel free to share!

**Comment by hbekel** [comment]
Glad it works for you.

> For any future viewers, a closing bracket is missing in the bashrun2.rc

There is definitely no bracket missing  in the distributed bashrun2.rc.

You might have had been a bracket missing in your bashrun2.rc, but that would lead to a general failure during startup and has nothing specifically to do with trying to use st as a terminal.

@scorpp Thanks for helping out :)

As st is quite minimal and I can't make sure all of bashrun's advertised features work with it, I'm reluctant to add explicit support for st for now.

**Comment by KaffeMyers** [comment]
The missing bracket comment was from his example, not in the distributed bashrn2.rc. :)

EDIT: too quick again, just pretend I didn't say anything. I'm just being a bit dense.

**Comment by hbekel** [comment]
@KaffeMyers: Please be more specific next time. The example from scorpp is not "missing" a closing braket, it just shows the beginning of a typical rc file. 

AND PLEASE STOP EDITING YOUR COMMENTS, DON'T ADD MORE ISSUES TO COMMENTS!

Closing this issue
